name: plastimatch
base: core22
version: '1.10.0'
summary: Snap package of Plastimatch for medical image processing
description: |
  This Snap package provides Plastimatch, an open-source software for medical
  image processing, primarily used in image registration and segmentation.

  By packaging Plastimatch as a Snap, this version ensures easy
  installation, automatic updates, and improved security through confinement.

  The package includes all necessary dependencies, making it a self-contained
  solution for users working with medical imaging applications.

grade: stable
confinement: strict

parts:
  plastimatch:
    plugin: dump
    source: local

    stage-packages:
      - libfuse3-3
      - libinsighttoolkit5.2
      - libpsm2-2-compat
      - gcc

    organize:
      libs/libplmsegment.so.1.10: lib/
      libs/libplmregister.so.1.10: lib/
      libs/libplmreconstruct.so.1.10: lib/
      libs/libplmdose.so.1.10: lib/
      libs/libplmutil.so.1.10: lib/
      libs/libplmbase.so.1.10: lib/
      libs/libplmsys.so.1.10: lib/
      libs/libblas.so.3: lib/
      libs/liblapack.so.3: lib/
      libs/libdcmdata.so.17: lib/
      libs/libdcmjpeg.so.17: lib/
      libs/liboflog.so.17: lib/
      libs/libofstd.so.17: lib/
      libs/libdcmimgle.so.17: lib/
      libs/libijg12.so.17: lib/
      libs/libijg16.so.17: lib/
      libs/libijg8.so.17: lib/
      libs/libminc2.so.5.3.0: lib/
      libs/libgfortran.so.5: lib/
      libs/libdlib.so.19.1: lib/
      libs/libxml2.so.2: lib/
      libs/libicuuc.so.72: lib/
      libs/libicudata.so.72: lib/
      libs/libjpeg.so.62: lib/
      libs/libhdf5_serial_cpp.so.103: lib/

apps:
  plastimatch:
    command: ./plastimatch
    plugs:
      - home
      - removable-media
      - optical-drive
